"""generate_presentation.py

Generates a 32-slide PowerPoint deck (Responsible AI & GitHub Copilot) using python-pptx.

Usage:
  pip install python-pptx
  python generate_presentation.py

Place your custom logo at assets/logo.png if you want it embedded in slides. If not present, the script will proceed without a logo.

Output:
  Responsible-AI-Copilot.pptx

Author: Generated by GitHub Copilot assistant
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import os

SLIDES_MD = 'slides_content.md'
OUTPUT_PPTX = 'Responsible-AI-Copilot.pptx'
LOGO_PATH = 'assets/logo.png'

# Theme colors
DARK_BLUE = RGBColor(11, 61, 145)  # #0B3D91
ACCENT_TEAL = RGBColor(0, 169, 165)
NEUTRAL_GRAY = RGBColor(100, 100, 100)

prs = Presentation()
prs.slide_height = Inches(7.5)
prs.slide_width = Inches(13.33)

# Utility to add title slide
def add_title_slide(title, subtitle, author, website, email, logo_path=None):
    slide_layout = prs.slide_layouts[5]
    slide = prs.slides.add_slide(slide_layout)
    left = Inches(0.5)
    top = Inches(0.5)

    # Title
    title_box = slide.shapes.add_textbox(left, top, Inches(8), Inches(1.2))
    tf = title_box.text_frame
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(36)
    p.font.bold = True
    p.font.color.rgb = DARK_BLUE

    # Subtitle
    sub_box = slide.shapes.add_textbox(left, Inches(1.4), Inches(8), Inches(0.8))
    stf = sub_box.text_frame
    sp = stf.paragraphs[0]
    sp.text = subtitle
    sp.font.size = Pt(20)
    sp.font.color.rgb = ACCENT_TEAL

    # Author / contact
    foot_box = slide.shapes.add_textbox(Inches(0.5), Inches(6.6), Inches(12.3), Inches(0.6))
    ft = foot_box.text_frame
    ft.word_wrap = True
    p1 = ft.paragraphs[0]
    p1.text = f"Author: {author}    Website: {website}    Email: {email}"
    p1.font.size = Pt(12)
    p1.font.color.rgb = NEUTRAL_GRAY

    # Logo on right
    if logo_path and os.path.exists(logo_path):
        try:
            slide.shapes.add_picture(logo_path, Inches(10.5), Inches(0.3), height=Inches(1.8))
        except Exception as e:
            print('Warning: could not add logo:', e)

# Utility to add standard content slide
def add_content_slide(title, bullets, notes=None, logo_path=None):
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title_shape = slide.shapes.title
    title_shape.text = title
    title_shape.text_frame.paragraphs[0].font.size = Pt(28)
    title_shape.text_frame.paragraphs[0].font.bold = True
    title_shape.text_frame.paragraphs[0].font.color.rgb = DARK_BLUE

    left = Inches(0.6)
    top = Inches(1.5)
    width = Inches(9.5)
    height = Inches(4.5)
    body = slide.shapes.add_textbox(left, top, width, height)
    tf = body.text_frame
    tf.margin_left = Inches(0.1)
    first = True
    for b in bullets:
        if first:
            p = tf.paragraphs[0]
            p.text = b
            first = False
        else:
            p = tf.add_paragraph()
            p.text = b
        p.level = 0
        p.font.size = Pt(18)
        p.font.color.rgb = RGBColor(32,32,32)

    # Notes: add as hidden slide notes
    if notes:
        notes_slide = slide.notes_slide
        notes_text_frame = notes_slide.notes_text_frame
        notes_text_frame.text = notes

    # Footer logo small
    if logo_path and os.path.exists(logo_path):
        try:
            slide.shapes.add_picture(logo_path, Inches(11.8), Inches(6.7), height=Inches(0.6))
        except Exception as e:
            pass

# Parse slides content from markdown
def parse_slides(md_path):
    slides = []
    if not os.path.exists(md_path):
        return slides
    with open(md_path, 'r', encoding='utf-8') as f:
        content = f.read()
    parts = content.split('\n---\n')
    for part in parts:
        lines = [l.rstrip() for l in part.strip().splitlines() if l.strip()!='']
        if not lines:
            continue
        title = lines[0].lstrip('# ').strip()
        bullets = []
        notes = None
        for l in lines[1:]:
            if l.startswith('Notes:'):
                notes = l[len('Notes:'):].strip()
            elif l.startswith('- '):
                bullets.append(l[2:].strip())
            else:
                bullets.append(l.strip())
        slides.append({'title': title, 'bullets': bullets, 'notes': notes})
    return slides


def main():
    slides = parse_slides(SLIDES_MD)
    author = 'ThandraRakesh'
    website = 'www.snp.com'
    email = 'sales@snp.com'

    # Title slide
    add_title_slide('Responsible AI & GitHub Copilot — Principles, Features, Agent Mode, Security, and Best Practices',
                    'Practical guide for teams and developers', author, website, email, logo_path=LOGO_PATH)

    # Add parsed slides
    for s in slides:
        add_content_slide(s['title'], s['bullets'], notes=s.get('notes'), logo_path=LOGO_PATH)

    prs.save(OUTPUT_PPTX)
    print('Generated', OUTPUT_PPTX)

if __name__ == '__main__':
    main()
